Upload

diff --git a/termux-url-opener b/termux-url-opener
--- a/termux-url-opener
+++ b/termux-url-opener
@@ -2,65 +2,77 @@
 
 clear
 kill_color=$'\e[0m'
-command -v youtube-dl &>/dev/null || printf "\e[031m Please install Youtube-dl manualy or run the the install.sh script again.\n$kill_color"
 
+command -v yt-dlp &>/dev/null || { 
+    printf "\e[031mPlease install yt-dlp manually!\n$kill_color"
+    exit 1
+}
 
+echo -e "\e[094m"
+echo " █████╗ ███████╗"
+echo "██╔══██╗╚══███╔╝"
+echo "███████║  ███╔╝ "
+echo "██╔══██║ ███╔╝  "
+echo "██║  ██║███████╗"
+echo "╚═╝  ╚═╝╚══════╝"
 
-echo -e "\e[031m" "  ╦═╗╔═╗  ╦ ╦╔╦╗  ╔╦╗╔═╗╦ ╦╔╗╔"
-echo -e "\e[031m" "  ╠╦╝╔═╝  ╚╦╝ ║    ║║║ ║║║║║║║"
-echo -e "\e[031m" "  ╩╚═╚═╝   ╩  ╩   ═╩╝╚═╝╚╩╝╝╚╝"
-echo -e "\e[036m" "╔════════════════════════════════════════╗"                                                                          
-echo -e "\e[032m" "║ ♚ Tool Name : RZ-YT-DOWN           ║"
-echo -e "\e[032m" "║ ♚ Author : RaZer                       ║"
-echo -e "\e[032m" "║ ♚ Github : g͟i͟t͟h͟u͟b͟.c͟o͟m͟/R͟a͟Z͟e͟r͟-R͟o͟V͟n͟s͟/    ║"
-echo -e "\e[032m" "║ ♚ y͟o͟u͟t͟u͟b͟e͟ : R͟a͟Z͟e͟r͟ s͟y͟b͟e͟a͟r͟ G͟a͟n͟       ║"
-echo -e "\e[036m" "╠════════════════════════════════════════╝"
-echo -e "\e[036m" "╠═▶ [𝗦𝗲𝗹𝗲𝗰𝘁 𝗔 𝐂𝐡𝐨𝐢𝐜𝐞]  ➳"
-echo -e "\e[032m" "╠═▶ 1. Music Mp3♫"
-echo -e "\e[032m" "╠═▶ 2. Video 360p"
-echo -e "\e[032m" "╠═▶ 3. Video 480p"
-echo -e "\e[032m" "╠═▶ 4. Video 720p"
-echo -e "\e[032m" "╠═▶ 5. Video 1080p"
-echo -e "\e[032m" "╠═▶ 6. Video 2160p"
-echo -e "\e[032m" "╠═▶ 7. Exit ʀᴢ-ʏᴛ-ᴅᴏᴡ" # Added
-command='-no-mtime -o /data/data/com.termux/files/home/storage/shared/Youtube/%(title)s.%(ext)s -f'
+echo -e "\e[036m╔════════════════════════════════════════════╗"
+echo -e "\e[032m║ ♚ Tool Name : AZ                           ║"
+echo -e "\e[032m║ ♚ Contributor : Azer                        ║"
+echo -e "\e[032m║ ♚ GitHub : https://github.com/JERIMARK     ║"
+echo -e "\e[032m║ ♚ YouTube : www.youtube.com/@azerrrr       ║"
+echo -e "\e[036m╚════════════════════════════════════════════╝"
 
-#Edit From Oak Atsume 
-printf "\e[032m ╚═:➤  $kill_color"
+printf "\e[032mEnter YouTube URL: $kill_color"
+read url
+
+if [[ -z $url ]]; then
+    clear
+    printf "\e[031mPlease enter a URL!\n$kill_color"
+    exit 1
+fi
+
+echo -e "\e[036m╔════════════════════════════════════╗"
+echo -e "\e[036m║        Select Download Option       ║"
+echo -e "\e[036m╠════════════════════════════════════╣"
+echo -e "\e[032m║ 1. Music Mp3♫                      ║"
+echo -e "\e[032m║ 2. Video 360p                       ║"
+echo -e "\e[032m║ 3. Video 480p                       ║"
+echo -e "\e[032m║ 4. Video 720p                       ║"
+echo -e "\e[032m║ 5. Video 1080p                      ║"
+echo -e "\e[032m║ 6. Video 2160p                      ║"
+echo -e "\e[032m║ 7. Exit                             ║"
+echo -e "\e[036m╚════════════════════════════════════╝"
+
+printf "\e[032mChoice: $kill_color"
 read option
 
-if [[ -z $option ]];
-then
-	clear
-	printf "\e[031m Please choose a option!\n$kill_color"
-else
-case $option in #Make Case list
-	1)
-	echo "$command 140" > ~/.config/youtube-dl/config #option 1
-	youtube-dl $1
-	;;
-	2)
-	echo "$command \"best[height<=360]\"" > ~/.config/youtube-dl/config #option 2
-	youtube-dl $1
-	;;
-	3)
-	echo "$command \"best[height<=480]\"" > ~/.config/youtube-dl/config #option 3
-	youtube-dl $1
-	;;
-	4)
-	echo "$command \"best[height<=720]\"" > ~/.config/youtube-dl/config #option 4
-	youtube-dl $1
-	;;
-	5)
-	echo "$command \"best[height<=1080]\"" > ~/.config/youtube-dl/config #option 5
-	youtube-dl $1
-	;;
-	6)
-	echo "$command \"best[height<=2160]\"" > ~/.config/youtube-dl/config
-    	youtube-dl $1
-	;;
-	7)
-	break
-	;;
-esac 
-fi
+output_path="/data/data/com.termux/files/home/storage/shared/Youtube/%(title)s.%(ext)s"
+
+case $option in
+    1)
+        yt-dlp -x --audio-format mp3 -o "$output_path" "$url"
+        ;;
+    2)
+        yt-dlp -f "best[height<=360]" -o "$output_path" "$url"
+        ;;
+    3)
+        yt-dlp -f "best[height<=480]" -o "$output_path" "$url"
+        ;;
+    4)
+        yt-dlp -f "best[height<=720]" -o "$output_path" "$url"
+        ;;
+    5)
+        yt-dlp -f "best[height<=1080]" -o "$output_path" "$url"
+        ;;
+    6)
+        yt-dlp -f "best[height<=2160]" -o "$output_path" "$url"
+        ;;
+    7)
+        exit 0
+        ;;
+    *)
+        printf "\e[031mInvalid option!\n$kill_color"
+        ;;
+esac
+
